[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=c++17", "-O2", "-Wall", "-Wextra", "-g",
            "-I", "library", "-I", "library/structure","library/algorithm", "library/graph", "library/string", "library/mathtype","library/utility"]
            
[repository]
name = "kyoprolibrary"
root = "."

[config]
repo_url = "https://github.com/Le-Leal/kyoproLibrary"
title = "Kyopro Library Documentation"
html_out_dir = "docs"