[config]
repo_url = "https://github.com/Le-Leal/kyoproLibrary"
html_out_dir = "docs"

[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=c++17", "-O2", "-Wall", "-Wextra", "-g",
            "-I", "library", "-I", "library/structure"]
            
[repository]
name = "kyoprolibrary"
root = "."